// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// count_barcodes_single
SEXP count_barcodes_single(SEXP seqs, SEXP guides);
RcppExport SEXP _gp_sa_screen_count_barcodes_single(SEXP seqsSEXP, SEXP guidesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type seqs(seqsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type guides(guidesSEXP);
    rcpp_result_gen = Rcpp::wrap(count_barcodes_single(seqs, guides));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gp_sa_screen_count_barcodes_single", (DL_FUNC) &_gp_sa_screen_count_barcodes_single, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_gp_sa_screen(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
