# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

setup_barcodes_combo_dual <- function(constants, guide_list) {
    .Call('_screenCounter_setup_barcodes_combo_dual', PACKAGE = 'screenCounter', constants, guide_list)
}

count_barcodes_combo_dual <- function(seqs, xptr, use_forward, use_reverse) {
    .Call('_screenCounter_count_barcodes_combo_dual', PACKAGE = 'screenCounter', seqs, xptr, use_forward, use_reverse)
}

report_barcodes_combo_dual <- function(xptr) {
    .Call('_screenCounter_report_barcodes_combo_dual', PACKAGE = 'screenCounter', xptr)
}

setup_barcodes_single <- function(constants, variables, n_sub, n_insert, n_del, n_total) {
    .Call('_screenCounter_setup_barcodes_single', PACKAGE = 'screenCounter', constants, variables, n_sub, n_insert, n_del, n_total)
}

count_barcodes_single <- function(seqs, xptr, use_forward, use_reverse) {
    .Call('_screenCounter_count_barcodes_single', PACKAGE = 'screenCounter', seqs, xptr, use_forward, use_reverse)
}

identify_barcodes_single <- function(seqs, xptr, use_forward, use_reverse) {
    .Call('_screenCounter_identify_barcodes_single', PACKAGE = 'screenCounter', seqs, xptr, use_forward, use_reverse)
}

basic_hash <- function(input) {
    .Call('_screenCounter_basic_hash', PACKAGE = 'screenCounter', input)
}

shift_hash <- function(input, coming) {
    .Call('_screenCounter_shift_hash', PACKAGE = 'screenCounter', input, coming)
}

export_basic_dictionary <- function(guides) {
    .Call('_screenCounter_export_basic_dictionary', PACKAGE = 'screenCounter', guides)
}

export_combined_dictionary <- function(constant, variable, n_sub, n_insert, n_del, n_total) {
    .Call('_screenCounter_export_combined_dictionary', PACKAGE = 'screenCounter', constant, variable, n_sub, n_insert, n_del, n_total)
}

