# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

count_barcodes_single <- function(seqs, guides) {
    .Call('_gp_sa_screen_count_barcodes_single', PACKAGE = 'gp.sa.screen', seqs, guides)
}

