# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

count_combo_barcodes_paired <- function(path1, constant1, reverse1, mismatches1, pool1, path2, constant2, reverse2, mismatches2, pool2, randomized, use_first, nthreads) {
    .Call('_screenCounter_count_combo_barcodes_paired', PACKAGE = 'screenCounter', path1, constant1, reverse1, mismatches1, pool1, path2, constant2, reverse2, mismatches2, pool2, randomized, use_first, nthreads)
}

count_combo_barcodes_single <- function(path, constant, strand, pool, mismatches, use_first, nthreads) {
    .Call('_screenCounter_count_combo_barcodes_single', PACKAGE = 'screenCounter', path, constant, strand, pool, mismatches, use_first, nthreads)
}

count_dual_barcodes <- function(path1, constant1, reverse1, mismatches1, pool1, path2, constant2, reverse2, mismatches2, pool2, randomized, use_first, diagnostics, nthreads) {
    .Call('_screenCounter_count_dual_barcodes', PACKAGE = 'screenCounter', path1, constant1, reverse1, mismatches1, pool1, path2, constant2, reverse2, mismatches2, pool2, randomized, use_first, diagnostics, nthreads)
}

count_random_barcodes <- function(path, constant, strand, mismatches, use_first, nthreads) {
    .Call('_screenCounter_count_random_barcodes', PACKAGE = 'screenCounter', path, constant, strand, mismatches, use_first, nthreads)
}

count_single_barcodes <- function(path, constant, strand, pool, mismatches, use_first, nthreads) {
    .Call('_screenCounter_count_single_barcodes', PACKAGE = 'screenCounter', path, constant, strand, pool, mismatches, use_first, nthreads)
}

match_barcodes <- function(sequences, choices, substitutions, reverse) {
    .Call('_screenCounter_match_barcodes', PACKAGE = 'screenCounter', sequences, choices, substitutions, reverse)
}

